version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/api"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/infra"
    schedule:
      interval: "daily"
    target-branch: "dev"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: 'dev'
