version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/api"
    schedule:
      interval: "monthly"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: "monthly"
    target-branch: "dev"
  - package-ecosystem: npm
    directory: "/infra
    schedule:
      interval: "monthly"
    target-branch: "dev"
