name: license-check
on: push
env:
  NODE_AUTH_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@findy-network'
          always-auth: true
      - name: install deps
        run: npm ci
      - name: run check
        run: |
          cp ${NPM_CONFIG_USERCONFIG} .
          npm run licenses:check
