name: release
on:
  push:
    tags:
      - "*"
jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: download test keys
        run: cd api/tools/isb && ./download-keys.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "version=$(./infra/tools/version.sh ./api)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-issuer-tool:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-issuer-tool:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-issuer-tool:latest
          cache-to: type=inline
          context: ./api
          file: ./api/Dockerfile
          build-args: |
            ISSUER_TOOL_SERVER_CERT_PATH=

  merge:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.AGENCY_RELEASER_ID }}
          private-key: ${{ secrets.AGENCY_RELEASER_KEY }}
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ steps.generate_token.outputs.token }}
      - name: merge
        run: |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master
