name: release
on:
  push:
    tags:
      - "*"
jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: echo "version=$(./infra/scripts/version.sh ./api)" >> $GITHUB_ENV

      - uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/findy-issuer-tool:${{ env.version }}
            ghcr.io/${{ github.repository_owner }}/findy-issuer-tool:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/findy-issuer-tool:latest
          cache-to: type=inline
          file: ./api/Dockerfile
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
            ISSUER_TOOL_SERVER_CERT_PATH=

  merge:
    needs: push-image
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: merge
        run: |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master
