name: test
on: push
jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@findy-network"
      - name: install deps
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: npm run build
      - name: test
        run: npm test
        env:
          AWS_ACCESS_KEY_ID: foo # needed for
          AWS_SECRET_ACCESS_KEY: bar # dynamodb connection
    services:
      dynamodb:
        image: amazon/dynamodb-local
        ports:
          - 8000:8000
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: install deps
        run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm test
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@findy-network"
      - name: install deps
        run: npm ci
      - name: run check
        run: |
          cp ${NPM_CONFIG_USERCONFIG} .
          npm run licenses:check
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@findy-network"
      - name: install deps
        run: |
          npm ci
          cd api && npm ci --legacy-peer-deps
          cd ../frontend && npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: run e2e
        run: npm run test:e2e
